import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Activity, ArrowLeft, Database, Download, LogOut, MapPin, Package, Plus, RefreshCw, Search, ShieldCheck, Store, Tags, Trash2, UserCog, Users, Warehouse } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import { ROLE_LABELS } from '../../lib/permissions';
import { useAuth, type AppRole } from '../auth/AuthContext';
import { recordActivity } from '../../services/activityLog';
import type { InventoryCategory, WarehouseConfig } from '../../types';

interface ProfileRow { id:string; full_name:string; email:string|null; role:AppRole; is_active:boolean; created_at:string; updated_at:string; }
interface ActivityRow { id:number; action:string; entity_type:string; entity_id:string|null; description:string; created_at:string; profiles:{full_name:string}|null; }
interface StateRow { payload:Record<string,unknown[]>; updated_at:string; version:number; }
type Section = 'overview'|'users'|'master'|'activity';
type MasterTab = 'categories'|'locations';

const roles:AppRole[] = ['master','manajer','purchasing','warehouse','viewer'];
const defaultCategories = ['Bahan Baku & Kimia Industri','Kemasan & Packaging','Suku Cadang & Sparepart','ATK & Perlengkapan Kantor','Elektrikal & IT Hardware','Lain-lain'].map((name,index)=>({id:`cat-default-${index}`,name,isActive:true}));
const defaultLocations:WarehouseConfig[] = [
  ['JKT','Warehouse Jakarta','warehouse','Jakarta'],['ACH','Warehouse Aceh','warehouse','Banda Aceh'],['RTI','Warehouse Roti','warehouse','Banda Aceh'],['BTR','Bintaro','store','Tangerang Selatan'],['GRH','Graha Raya','store','Tangerang'],['TMP','TMP','store','Banda Aceh'],['LMT','Lamteh','store','Banda Aceh'],['BTH','Batoh','store','Banda Aceh'],['SRT','Store Roti Kiri','store','Banda Aceh'],
].map(([code,name,type,city],index)=>({id:`location-default-${index}`,code,name,type:type as 'warehouse'|'store',city,isActive:true}));
const dataKeys = [['kiri_warehouse_items','SKU'],['kiri_suppliers','Supplier'],['kiri_requisitions','PR'],['kiri_purchase_orders','PO'],['kiri_goods_receipts','GRN'],['kiri_stock_opnames','Opname'],['kiri_store_transfers','Transfer']] as const;
const nav = [{id:'overview',label:'Ringkasan',icon:ShieldCheck},{id:'users',label:'Pengguna & Role',icon:UserCog},{id:'master',label:'Master Data',icon:Database},{id:'activity',label:'Aktivitas',icon:Activity}] as const;

const StatusButton:React.FC<{active:boolean;disabled?:boolean;onClick:()=>void}> = ({active,disabled,onClick}) => <button disabled={disabled} onClick={onClick} className={`min-h-9 rounded-full px-3 text-[10px] font-bold disabled:opacity-50 ${active?'bg-[#e8f7e4] text-[#356d2f]':'bg-[#efefec] text-[#666]'}`}>{active?'Aktif':'Nonaktif'}</button>;

export const AdminDashboard:React.FC = () => {
  const {profile,signOut} = useAuth();
  const [profiles,setProfiles] = useState<ProfileRow[]>([]);
  const [activities,setActivities] = useState<ActivityRow[]>([]);
  const [appState,setAppState] = useState<StateRow|null>(null);
  const [loading,setLoading] = useState(true);
  const [savingId,setSavingId] = useState('');
  const [message,setMessage] = useState('');
  const [categories,setCategories] = useState<InventoryCategory[]>([]);
  const [warehouses,setWarehouses] = useState<WarehouseConfig[]>([]);
  const [newCategory,setNewCategory] = useState('');
  const [newLocation,setNewLocation] = useState({code:'',name:'',city:'',type:'warehouse' as 'warehouse'|'store'});
  const [section,setSection] = useState<Section>('overview');
  const [masterTab,setMasterTab] = useState<MasterTab>('categories');
  const [search,setSearch] = useState('');

  const load = useCallback(async()=>{
    if(!supabase)return; setLoading(true); setMessage('');
    const [p,a,s] = await Promise.all([
      supabase.from('profiles').select('id,email,full_name,role,is_active,created_at,updated_at').order('created_at',{ascending:false}),
      supabase.from('activity_log').select('id,action,entity_type,entity_id,description,created_at,profiles(full_name)').order('created_at',{ascending:false}).limit(100),
      supabase.from('app_state').select('payload,updated_at,version').eq('id',1).maybeSingle(),
    ]);
    const error=p.error||a.error||s.error;
    if(error)setMessage(error.message); else {setProfiles((p.data||[]) as ProfileRow[]);setActivities((a.data||[]) as unknown as ActivityRow[]);setAppState(s.data as StateRow|null);} setLoading(false);
  },[]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{if(!appState)return;setCategories((appState.payload.kiri_inventory_categories?.length?appState.payload.kiri_inventory_categories:defaultCategories) as unknown as InventoryCategory[]);setWarehouses((appState.payload.kiri_warehouses?.length?appState.payload.kiri_warehouses:defaultLocations) as unknown as WarehouseConfig[]);},[appState]);

  const saveSettings=async(nextCategories=categories,nextWarehouses=warehouses)=>{
    if(!supabase||!appState)return; setMessage('');
    const payload={...appState.payload,kiri_inventory_categories:nextCategories,kiri_warehouses:nextWarehouses};
    const {error}=await supabase.from('app_state').upsert({id:1,payload,updated_at:new Date().toISOString()});
    if(error)setMessage(error.message);else{setMessage('Perubahan master data berhasil disimpan.');await recordActivity('system','warehouse_settings',null,'Admin memperbarui kategori atau lokasi gudang');await load();}
  };
  const addCategory=()=>{const name=newCategory.trim();if(!name)return setMessage('Nama kategori wajib diisi.');if(categories.some(x=>x.name.toLowerCase()===name.toLowerCase()))return setMessage('Kategori tersebut sudah ada.');const next=[...categories,{id:`cat-${Date.now()}`,name,isActive:true}];setCategories(next);setNewCategory('');void saveSettings(next,warehouses);};
  const addLocation=()=>{const code=newLocation.code.trim().toUpperCase(),name=newLocation.name.trim();if(!code||!name)return setMessage('Kode dan nama lokasi wajib diisi.');if(warehouses.some(x=>x.code.toLowerCase()===code.toLowerCase()))return setMessage('Kode lokasi sudah digunakan.');const next=[...warehouses,{id:`location-${Date.now()}`,code,name,city:newLocation.city.trim()||'Indonesia',type:newLocation.type,isActive:true}];setWarehouses(next);setNewLocation({code:'',name:'',city:'',type:'warehouse'});void saveSettings(categories,next);};
  const updateCategory=(id:string,changes:Partial<InventoryCategory>)=>{const next=categories.map(x=>x.id===id?{...x,...changes}:x);setCategories(next);void saveSettings(next,warehouses);};
  const updateLocation=(id:string,changes:Partial<WarehouseConfig>)=>{const next=warehouses.map(x=>x.id===id?{...x,...changes}:x);setWarehouses(next);void saveSettings(categories,next);};
  const updateProfile=async(row:ProfileRow,changes:Partial<Pick<ProfileRow,'role'|'is_active'>>)=>{if(!supabase||row.id===profile.id)return;setSavingId(row.id);const {error}=await supabase.from('profiles').update({...changes,updated_at:new Date().toISOString()}).eq('id',row.id);if(error)setMessage(error.message);else{await recordActivity('system','profile',row.id,`Admin mengubah akun ${row.full_name}`);await load();}setSavingId('');};
  const totals=useMemo(()=>Object.fromEntries(dataKeys.map(([key])=>[key,appState?.payload?.[key]?.length||0])),[appState]);
  const query=search.trim().toLowerCase();
  const visibleCategories=categories.filter(x=>!query||x.name.toLowerCase().includes(query));
  const visibleLocations=warehouses.filter(x=>!query||`${x.code} ${x.name} ${x.city} ${x.type}`.toLowerCase().includes(query));
  const downloadBackup=()=>{if(!appState)return;const blob=new Blob([JSON.stringify({exportDate:new Date().toISOString(),...appState.payload},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`kiri-wms-admin-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);};

  return <div className="min-h-screen bg-[#f3f2ef] text-[#242424] md:flex">
    <aside className="hidden w-[248px] shrink-0 border-r border-[#e7e5e0] bg-[#fbfbf9] p-3 md:flex md:min-h-screen md:flex-col">
      <div className="flex items-center gap-3 px-2 py-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#252525] text-[#82dd70]"><ShieldCheck size={20}/></span><div><p className="text-sm font-extrabold">Kiri Supply</p><p className="text-[10px] text-[#888781]">Administration</p></div></div>
      <nav className="mt-6 space-y-1">{nav.map(({id,label,icon:Icon})=><button key={id} onClick={()=>setSection(id)} className={`flex min-h-11 w-full items-center gap-3 rounded-xl px-3 text-left text-[13px] ${section===id?'bg-[#82dd70] font-bold text-[#183316]':'font-medium text-[#676762] hover:bg-[#f0efeb]'}`}><Icon size={18}/>{label}</button>)}</nav>
      <div className="mt-auto space-y-2"><a href="/" className="flex min-h-11 items-center gap-2 rounded-xl border bg-white px-3 text-xs font-bold"><ArrowLeft size={15}/>Kembali ke aplikasi</a><button onClick={()=>void signOut()} className="flex min-h-11 w-full items-center gap-2 rounded-xl px-3 text-xs font-bold text-rose-700 hover:bg-rose-50"><LogOut size={15}/>Keluar</button><div className="rounded-xl bg-[#f0efeb] p-3"><p className="truncate text-xs font-bold">{profile.fullName}</p><p className="text-[10px] uppercase text-[#888781]">Master administrator</p></div></div>
    </aside>

    <div className="min-w-0 flex-1"><header className="sticky top-0 z-30 border-b border-[#e7e5e0] bg-[#f3f2ef]/95 backdrop-blur-lg"><div className="flex min-h-[68px] items-center justify-between gap-3 px-4 sm:px-6 lg:px-8"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#8a8983]">Admin Console</p><h1 className="text-lg font-black">{nav.find(x=>x.id===section)?.label}</h1></div><div className="flex gap-2"><button onClick={()=>void load()} className="flex h-10 w-10 items-center justify-center rounded-xl border bg-white"><RefreshCw size={16} className={loading?'animate-spin':''}/></button><button onClick={downloadBackup} className="hidden min-h-10 items-center gap-2 rounded-xl bg-[#252525] px-3 text-xs font-bold text-white sm:flex"><Download size={15} className="text-[#82dd70]"/>Backup</button><a href="/" className="flex h-10 w-10 items-center justify-center rounded-xl border bg-white md:hidden"><ArrowLeft size={16}/></a></div></div><nav className="flex gap-1 overflow-x-auto px-3 pb-2 md:hidden">{nav.map(({id,label,icon:Icon})=><button key={id} onClick={()=>setSection(id)} className={`flex min-h-10 shrink-0 items-center gap-2 rounded-xl px-3 text-xs font-bold ${section===id?'bg-[#252525] text-white':'bg-white text-[#686762]'}`}><Icon size={15} className={section===id?'text-[#82dd70]':''}/>{label}</button>)}</nav></header>

      <main className="mx-auto max-w-[1440px] space-y-4 p-3 pb-12 sm:p-6 lg:p-8">
        {message&&<div role="status" className={`rounded-xl border px-4 py-3 text-xs font-semibold ${/berhasil/i.test(message)?'border-green-200 bg-green-50 text-green-800':'border-amber-200 bg-amber-50 text-amber-800'}`}>{message}</div>}

        {section==='overview'&&<><section className="flex flex-col justify-between gap-3 rounded-2xl border bg-white p-5 sm:flex-row sm:items-center"><div><p className="text-xs font-semibold text-[#777773]">Selamat datang, {profile.fullName}</p><h2 className="mt-1 text-xl font-black sm:text-2xl">Kondisi sistem hari ini</h2><p className="mt-1 text-xs text-[#888781]">Pantau pengguna, data operasional, dan master gudang.</p></div><button onClick={()=>setSection('master')} className="min-h-11 rounded-xl bg-[#82dd70] px-4 text-xs font-bold text-[#183316]">Kelola master data</button></section>
          <section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[[Users,profiles.length,'Total akun',`${profiles.filter(x=>x.is_active).length} aktif`],[Package,totals.kiri_warehouse_items||0,'Master SKU',`${categories.filter(x=>x.isActive).length} kategori aktif`],[Warehouse,warehouses.filter(x=>x.type==='warehouse'&&x.isActive).length,'Gudang aktif',`${warehouses.filter(x=>x.type==='store'&&x.isActive).length} store`],[Activity,activities.length,'Aktivitas',appState?.updated_at?`Sync ${new Date(appState.updated_at).toLocaleDateString('id-ID')}`:'Belum sinkron']].map(([Icon,value,label,note])=>{const I=Icon as typeof Users;return <article key={String(label)} className="rounded-2xl border bg-white p-4"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#f0efeb]"><I size={17}/></span><p className="mt-3 text-2xl font-black">{String(value)}</p><p className="text-xs font-bold">{String(label)}</p><p className="mt-1 text-[10px] text-[#888781]">{String(note)}</p></article>;})}</section>
          <section className="rounded-2xl border bg-white p-4"><h3 className="font-black">Data operasional</h3><p className="text-[10px] text-[#888781]">Snapshot data tersimpan saat ini</p><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-7">{dataKeys.map(([key,label])=><div key={key} className="rounded-xl bg-[#f7f6f3] p-3"><p className="text-lg font-black">{totals[key]||0}</p><p className="text-[10px] font-semibold text-[#777773]">{label}</p></div>)}</div></section></>}

        {section==='users'&&<section className="overflow-hidden rounded-2xl border bg-white"><div className="border-b p-5"><h2 className="font-black">Pengguna & hak akses</h2><p className="text-[11px] text-[#888781]">Atur role dan status akun. Akun Anda sendiri dilindungi.</p></div><div className="divide-y">{profiles.map(row=><article key={row.id} className="grid gap-3 p-4 sm:grid-cols-[minmax(220px,1fr)_180px_110px_100px] sm:items-center"><div><p className="text-sm font-bold">{row.full_name||'Tanpa nama'}</p><p className="text-[11px] text-[#888781]">{row.email||'Akun pengguna'}</p></div><select value={row.role} disabled={row.id===profile.id||savingId===row.id} onChange={e=>void updateProfile(row,{role:e.target.value as AppRole})} className="min-h-11 rounded-xl border bg-white px-3 text-xs">{roles.map(role=><option key={role} value={role}>{ROLE_LABELS[role]}</option>)}</select><StatusButton active={row.is_active} disabled={row.id===profile.id||savingId===row.id} onClick={()=>void updateProfile(row,{is_active:!row.is_active})}/><p className="text-[10px] text-[#888781]">{new Date(row.created_at).toLocaleDateString('id-ID')}</p></article>)}</div></section>}

        {section==='master'&&<section className="overflow-hidden rounded-2xl border bg-white"><div className="border-b p-4 sm:p-5"><h2 className="font-black">Master Data</h2><p className="text-[11px] text-[#888781]">Kategori barang dan jaringan gudang/store.</p><div className="mt-4 flex gap-1 rounded-xl bg-[#f1f0ec] p-1">{[{id:'categories' as const,label:`Kategori (${categories.length})`,icon:Tags},{id:'locations' as const,label:`Lokasi (${warehouses.length})`,icon:MapPin}].map(({id,label,icon:Icon})=><button key={id} onClick={()=>{setMasterTab(id);setSearch('');}} className={`flex min-h-10 flex-1 items-center justify-center gap-2 rounded-lg text-xs font-bold ${masterTab===id?'bg-white shadow-sm':'text-[#777773]'}`}><Icon size={15}/>{label}</button>)}</div></div>
          <div className="grid lg:grid-cols-[330px_minmax(0,1fr)]"><div className="border-b bg-[#faf9f6] p-4 lg:border-b-0 lg:border-r"><h3 className="text-sm font-black">Tambah {masterTab==='categories'?'kategori':'lokasi'}</h3><p className="mt-1 text-[10px] text-[#888781]">{masterTab==='categories'?'Nama harus jelas dan tidak duplikat.':'Kode lokasi harus unik dan singkat.'}</p>{masterTab==='categories'?<div className="mt-4 space-y-2"><input value={newCategory} onChange={e=>setNewCategory(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')addCategory();}} placeholder="Nama kategori baru" className="h-11 w-full rounded-xl border bg-white px-3 text-sm"/><button onClick={addCategory} className="flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-[#82dd70] text-xs font-bold text-[#183316]"><Plus size={15}/>Tambah kategori</button></div>:<div className="mt-4 grid grid-cols-2 gap-2"><input value={newLocation.code} onChange={e=>setNewLocation(x=>({...x,code:e.target.value}))} placeholder="Kode" maxLength={8} className="h-11 rounded-xl border px-3 text-sm uppercase"/><select value={newLocation.type} onChange={e=>setNewLocation(x=>({...x,type:e.target.value as 'warehouse'|'store'}))} className="h-11 rounded-xl border bg-white px-2 text-sm"><option value="warehouse">Gudang</option><option value="store">Store</option></select><input value={newLocation.name} onChange={e=>setNewLocation(x=>({...x,name:e.target.value}))} placeholder="Nama lokasi" className="col-span-2 h-11 rounded-xl border px-3 text-sm"/><input value={newLocation.city} onChange={e=>setNewLocation(x=>({...x,city:e.target.value}))} placeholder="Kota" className="col-span-2 h-11 rounded-xl border px-3 text-sm"/><button onClick={addLocation} className="col-span-2 flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[#82dd70] text-xs font-bold text-[#183316]"><Plus size={15}/>Tambah lokasi</button></div>}</div>
            <div className="min-w-0 p-4 sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="text-sm font-black">Daftar {masterTab==='categories'?'kategori barang':'gudang & store'}</h3><p className="text-[10px] text-[#888781]">Nonaktifkan data lama agar histori tetap aman.</p></div><label className="relative sm:w-64"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#999]"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari master data..." className="h-10 w-full rounded-xl border pl-9 pr-3 text-xs"/></label></div><div className="mt-4 space-y-2">{masterTab==='categories'?visibleCategories.map(category=><div key={category.id} className="flex items-center gap-3 rounded-xl border p-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-[#eef8eb] text-[#43833a]"><Tags size={16}/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{category.name}</p><p className="text-[10px] text-[#888781]">{category.isActive?'Tersedia untuk SKU baru':'Diarsipkan'}</p></div><StatusButton active={category.isActive} onClick={()=>updateCategory(category.id,{isActive:!category.isActive})}/><button onClick={()=>{if(window.confirm(`Hapus kategori ${category.name}?`)){const next=categories.filter(x=>x.id!==category.id);setCategories(next);void saveSettings(next,warehouses);}}} className="flex h-9 w-9 items-center justify-center rounded-lg text-rose-600"><Trash2 size={15}/></button></div>):visibleLocations.map(location=>{const Icon=location.type==='warehouse'?Warehouse:Store;return <div key={location.id} className="flex items-center gap-3 rounded-xl border p-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#eef8eb] text-[#43833a]"><Icon size={17}/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{location.name} <span className="font-mono text-[9px] text-[#888]">{location.code}</span></p><p className="text-[10px] capitalize text-[#888781]">{location.type==='warehouse'?'Gudang':'Store'} · {location.city}</p></div><StatusButton active={location.isActive} onClick={()=>updateLocation(location.id,{isActive:!location.isActive})}/><button onClick={()=>{if(window.confirm(`Hapus lokasi ${location.name}?`)){const next=warehouses.filter(x=>x.id!==location.id);setWarehouses(next);void saveSettings(categories,next);}}} className="flex h-9 w-9 items-center justify-center rounded-lg text-rose-600"><Trash2 size={15}/></button></div>;})}{((masterTab==='categories'&&!visibleCategories.length)||(masterTab==='locations'&&!visibleLocations.length))&&<p className="rounded-xl border border-dashed p-8 text-center text-xs text-[#777]">Data tidak ditemukan.</p>}</div></div></div></section>}

        {section==='activity'&&<section className="overflow-hidden rounded-2xl border bg-white"><div className="border-b p-5"><h2 className="font-black">Aktivitas terbaru</h2><p className="text-[11px] text-[#888781]">Jejak perubahan operasional dan administratif.</p></div><div className="divide-y">{activities.length===0?<p className="p-8 text-center text-sm text-[#777]">Belum ada aktivitas.</p>:activities.map(item=><div key={item.id} className="flex items-start gap-3 p-4"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-[#82dd70]"/><div className="min-w-0 flex-1"><p className="text-sm font-bold">{item.description}</p><p className="text-[10px] text-[#888781]">{item.profiles?.full_name||'Pengguna'} · {item.entity_type}</p></div><time className="shrink-0 text-right text-[10px] text-[#888781]">{new Date(item.created_at).toLocaleString('id-ID')}</time></div>)}</div></section>}
      </main>
    </div>
  </div>;
};
